import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
	//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
public class OneOfEachStats {
	public static void main (String[] args) {
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
        Random generator = new Random(seed);  
		double sumNumberOfChildren = 0;
		int NumberOf2Children = 0;
		int NumberOf3Children = 0;
		int NumberOf4OrMoreChildren = 0;
		
		for (int i = 0 ; i < T ; i++) {
			boolean girl = false;
			boolean boy = false; 
			int count = 0;  
			while (!(girl && boy)){
				double random = generator.nextDouble();
				if (random <= 0.5){
				girl = true; 
				//System.out.print("g ");
				} else {
					boy = true;
					//System.out.print("b ");
				}
				count++; 
			}
			//System.out.println();
			sumNumberOfChildren = sumNumberOfChildren + count;

			if (count == 2) { 
				NumberOf2Children++;
			 }
			if (count == 3) { 
				NumberOf3Children++;
			}
			if (count >= 4) { 
				NumberOf4OrMoreChildren++;
			} 
		}
			String mostCommonNumber = ""; 
			if ((NumberOf2Children >= NumberOf3Children) && (NumberOf2Children >= NumberOf4OrMoreChildren)) {
				mostCommonNumber = "2.";
			} else {
				if ((NumberOf3Children >= NumberOf2Children) && (NumberOf3Children >= NumberOf4OrMoreChildren)) {
					mostCommonNumber = "3."; 
				} else {
						mostCommonNumber = "4 or more.";		
					}
				}
		

		System.out.println("Average: " + ((double) sumNumberOfChildren / T) + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + NumberOf2Children);
		System.out.println("Number of families with 3 children: " + NumberOf3Children);
		System.out.println("Number of families with 4 or more children: " + NumberOf4OrMoreChildren);
		System.out.println("The most common number of children is " + mostCommonNumber) ;
	}
}
	

